name: Run

on: [push]

jobs:
  Build:
    runs-on: windows-2025

    steps:
      - name: Test
        shell: powershell
        run: |
          echo fuckyou > a.txt
          mkdir fuck
          pwd
          cd fuck
          pwd

