name: Run

on: [push]

jobs:
  Build:
    runs-on: windows-2025

    steps:
      - name: Deploy rclone
        shell: pwsh
        run: |
          Invoke-WebRequest 'https://downloads.rclone.org/v1.69.0/rclone-v1.69.0-windows-amd64.zip' -OutFile rclone.zip
          unzip rclone.zip
          echo '${{ secrets.RCLONE_CONF }}' > ./rclone-v1.69.0-windows-amd64/rclone.conf
          del rclone.zip
          mkdir temp
          cd temp
          touch fuckyou123.txt

      - name: 显示文件树。
        shell: cmd
        run: tree /F

      - name: Upload the file to OneDrive with rclone
        shell: pwsh
        run: |
          cd rclone-v1.69.0-windows-amd64
          ls
          ./rclone.exe --config rclone.conf copy -P ../temp "OneDrive-30GB-ty:"

